### ISSUE TITLE
The issue regarding the RSBench_train.json file

### ISSUE THREAD

**Issue by y-x-x123** [lx709/VRSBench#1]
Hello, in Hugging Face. There are many repeated Q&As questions for the same image in the RSBench_train.json, which are different from the data displayed in the Viewer.
![399DB464A7FE6436FB5E39DD200BDC21](https://github.com/lx709/VRSBench/assets/73542480/0817e2cc-7e7d-4eb5-b3d7-905096798dae)

**Comment by lx709** [comment]
Dear @y-x-x123 , thanks for pointing this out. There was a small bug when preparing LLAVA-format training data from our annotations. It was fixed now and a new file was uploaded in the Huggingface repo.
