### ISSUE TITLE
code and models

### ISSUE THREAD

**Issue by scott-vsi** [lx709/VRSBench#3]
Any update on when you plan to release the code and baseline models?

**Comment by lx709** [comment]
Dear @scott-vsi , thanks for your interest. If you mean the codes of baseline models, you can directly find them in their official repo. If you mean the codes for evaluation, please wait a litter bit, since we expect to get notification of paper acceptance on Sep 26th.

**Comment by scott-vsi** [comment]
Got it. Thank you. Good luck with your submission!
