### ISSUE TITLE
Access to OneDrive Link Denied

### ISSUE THREAD

**Issue by MonsterZhZh** [lx709/VRSBench#5]
Thank you for sharing such outstanding work. When reviewing the benchmark results and accessing the OneDrive link, I encountered the following issue: 
<img width="841" alt="image" src="https://github.com/user-attachments/assets/f47bb188-48ad-418d-97d1-572790d995ca">

Could it be due to a lack of access permissions? How do you think I should resolve this?

**Comment by lx709** [comment]
Hello @MonsterZhZh , please check the updated link in readme.
